# seichiassist 設定ファイル
# このファイルを削除orリネームしてからサーバを起動するとデフォルトの設定ファイルが再生成されます(エラーが出たときは真っ先に試しましょう)

# MySQLデータベースへの接続設定
# xamppの設定を変えていなければデフォルトの値で問題ありません
host: 'localhost'
port: '3306'
db: 'seichiassist'
id: 'root'
pw: ''

# サーバ識別設定
# 複数サーバ構成にする場合はこの値をサーバごとに変更します
servernum: '1'

# 色々な設定、説明は割愛
defaultmineamount: '3'
minutespeedamount: '0.01'
onlineplayersamount: '0.5'
presentinterval: '1000'
dualbreaklevel: '10'
trialbreaklevel: '20'
explosionlevel: '30'
thunderstormlevel: '40'
blizzardlevel: '50'
meteolevel: '60'
gravitylevel: '100'
multipleidblockbreaklevel: '1'
dropexplevel1: '6'
dropexplevel2: '10'
dropexplevel3: '16'
dropexplevel4: '24'
dropexplevel5: '34'
dropexplevel6: '46'
dropexplevel7: '60'
dropexplevel8: '76'
dropexplevel9: '94'
dropexplevel10: '114'
passiveportalinventorylevel: '1'
dokodemoenderlevel: '25'

# MineStackの開放レベルの設定
minestacklevel1: '12'
minestacklevel2: '17'
minestacklevel3: '22'
minestacklevel4: '27'
minestacklevel5: '32'
minestacklevel6: '37'
minestacklevel7: '42'
minestacklevel8: '47'
minestacklevel9: '52'
minestacklevel10: '57'
minestacklevel11: '62'
minestacklevel12: '67'
minestacklevel13: '72'
minestacklevel14: '77'
minestacklevel15: '82'
minestacklevel16: '87'
minestacklevel17: '92'
minestacklevel18: '97'
minestacklevel19: '102'
minestacklevel20: '107'
minestacklevel21: '112'
minestacklevel22: '117'
minestacklevel23: '122'
minestacklevel24: '127'
minestacklevel25: '132'
minestacklevel26: '137'
minestacklevel27: '142'
minestacklevel28: '147'
minestacklevel29: '152'
minestacklevel30: '157'
minestacklevel31: '162'
minestacklevel32: '167'
minestacklevel33: '172'
minestacklevel34: '177'
minestacklevel35: '182'
minestacklevel36: '187'
minestacklevel37: '192'
minestacklevel38: '197'

# レベルアップ時にプレイヤーに表示されるメッセージの設定
lv1message: "整地鯖では整地をするとレベルが上がり、様々な恩恵が受けられます。\n初めての方は整地ワールドで掘ってレベルを上げてみましょう！\n木の棒を右クリックしてメニューを開き右上のビーコンボタンをクリック！"
lv2message: "おめでとうございます！最初のレベルアップです！\nレベル8に到達すると整地するだけで経験値がもらえるようになります。"
lv3message: "やけに早く掘れる気がする…？それは仕様です＾＾\n整地鯖では接続人数や採掘量に応じて採掘速度にブーストが掛かります。"
lv4message: "整地鯖では死んでもロストしません。気軽に冒険、整地してくださいね。\nそういえば当鯖の「ルール」もう確認しましたか？\n手遅れになる前に確認しておきましょうネ。木の棒メニューからどうぞ。"
lv5message: "Dynmapでどこに誰がいるのか、何があるのかなどを見ることができます。\nURLはこちら→http://mc.seichi.click:8123"
lv6message: "ブランチマイニングは資源ワールドでお願いします。\nスポーンワールドから行くことが出来ます。行き方覚えてますか？\n木の棒メニューのビーコンボタンをクリックするとすぐ行けますよ！"
lv7message: "あと300ブロックほど整地するとガチャ券を獲得できます！\nガチャ券を右クリックすると豪華景品が獲得できるかも？"
lv8message: "おめでとう！新しいパッシブスキル[追加経験値獲得]を解除しました。\n特定のブロック破壊で確率で追加経験値を獲得できるようになりました！"
lv9message: "整地鯖をもっと良くするために、是非JPMCSに投票をお願いします。\n1日1回投票出来ます。投票すると様々な特典を受け取れます！\nURLはこちら→https://minecraft.jp/servers/seichi.click/vote"
lv10message: "初めてのアクティブスキル[デュアルブレイク]を習得できます！\n習得するには木の棒メニューのスキルブックをクリック！\nレベル12に到達するとMineStack機能が使えるようになります。\nブロック破壊スキルでは溶岩も消去することができますが溶岩1個につきブロック10個分の耐久値を消費します。"
lv11message: "そろそろ家建てません…？自分の家はメインワールドで建てることができます。\n他人の保護の無い所に保護を設定してから建てましょう。\n保護方法は公式wikiに詳しい説明があります。木の棒メニューからどうぞ。\n自分のチェストは設定した保護内に置けば自動でロックされます。"
lv12message: "MineStack機能を解除しました！木の棒メニューから呼び出せます。\n対象ブロックを無限にスタック出来、いつでも取り出せます。\nスタック出来るブロックはレベルを上げると増えていきます。\n土と草ブロックがスタックされるようになります。\nレベル16に到達すると四次元ポケットが使えるようになります。"
lv13message: "建築の時など、採掘速度のブースト効果が邪魔な時は\n木の棒メニューから効果のONとOFFを変更できます。"
lv14message: "「ガチャ券がイチイチ地面に落っこちるのがうざい！」\nって人に朗報です。木の棒メニューからガチャ券の取得方法を変更できます。"
lv15message: "家を建てたら木の棒メニューからホームポイントを設定しておきましょう。\nどこからでもクリック1つで自宅へ瞬間移動できますよ！"
lv16message: "新しいパッシブスキル[4次元ポケット]を解除しました！\n四次元ポケットは木の棒メニューから開くことが出来ます。\nレベルを上げるとポケットの容量が増えていきます。"
lv17message: "MineStack機能の対象ブロックが増えました！\n新たに丸石と石がスタックされるようになります。"
lv18message: "整地の際に獲得できる経験値量が増えました。\n経験値量は10レベルごとに増加し、スキルがより長く使えるようになります！"
lv20message: "新しいアクティブスキル[トリアルブレイク]を習得できます！\n習得するには木の棒メニューのスキルブックをクリック！"
lv22message: "MineStack機能の対象ブロックが増えました！\n新たに花崗岩と閃緑岩、安山岩がスタックされるようになります。"
lv25message: "どこでもエンダーチェスト機能を解除しました！\n木の棒メニューから呼び出せます。"
lv27message: "MineStack機能の対象ブロックが増えました！\n新たに各種原木がスタックされるようになります。"
lv28message: "整地の際に獲得できる経験値量が増えました。"
lv30message: "新しいアクティブスキル[エクスプロージョン]を習得できます！\n習得するには木の棒メニューのスキルブックをクリック！"
lv32message: "MineStack機能の対象ブロックが増えました！\n新たに砂利と砂、砂岩がスタックされるようになります。"
lv37message: "MineStack機能の対象ブロックが増えました！\n新たにネザーラックとソウルサンドがスタックされるようになります。"
lv38message: "整地の際に獲得できる経験値量が増えました。"
lv40message: "新しいアクティブスキルを習得できます！\n習得するには木の棒メニューのスキルブックをクリック！\nツリーが分かれていますので、お好きなスキルをドウゾ。"
lv42message: "MineStack機能の対象ブロックが増えました！\n新たに石炭と石炭鉱石がスタックされるようになります。"
lv46message: "四次元ポケットの容量が増加しました！"
lv47message: "MineStack機能の対象ブロックが増えました！\n新たにエンドストーンがスタックされるようになります。"
lv48message: "整地の際に獲得できる経験値量が増えました。"
lv52message: "MineStack機能の対象ブロックが増えました！\n新たに鉄鉱石と黒曜石がスタックされるようになります。"
lv56message: "四次元ポケットの容量が増加しました！"
lv57message: "MineStack機能の対象ブロックが増えました！\n新たに氷塊がスタックされるようになります。"
lv58message: "整地の際に獲得できる経験値量が増えました。"
lv62message: "MineStack機能の対象ブロックが増えました！\n新たにクォーツとクォーツ鉱石がスタックされるようになります。"
lv66message: "四次元ポケットの容量が増加しました！"
lv67message: "MineStack機能の対象ブロックが増えました！\n新たにマグマブロックがスタックされるようになります。"
lv68message: "整地の際に獲得できる経験値量が増えました。"
lv72message: "MineStack機能の対象ブロックが増えました！\n新たに金鉱石とグロウストーンがスタックされるようになります。"
lv77message: "MineStack機能の対象ブロックが増えました！\n新たにオークの木材とオークのフェンスがスタックされるようになります。"
lv78message: "整地の際に獲得できる経験値量が増えました。"
lv82message: "MineStack機能の対象ブロックが増えました！\n新たにレッドストーンとレッドストーン鉱石がスタックされるようになります。"
lv87message: "MineStack機能の対象ブロックが増えました！\n新たにラピスラズリとラピスラズリ鉱石がスタックされるようになります。"
lv88message: "整地の際に獲得できる経験値量が増えました。"
lv92message: "MineStack機能の対象ブロックが増えました！\n新たにダイヤモンドとダイヤモンド鉱石がスタックされるようになります。"
lv97message: "MineStack機能の対象ブロックが増えました！\n新たにエメラルドとエメラルド鉱石がスタックされるようになります。"
lv98message: "整地の際に獲得できる経験値量が増えました。"
lv102message: "MineStack機能の対象ブロックが増えました！\n新たにがちゃりんごとエンチャントの瓶がスタックされるようになります。"
lv107message: "MineStack機能の対象ブロックが増えました！\n新たに赤い砂と赤い砂岩がスタックされるようになります。"
lv112message: "MineStack機能の対象ブロックが増えました！\n新たに堅焼き粘土がスタックされるようになります。"
lv117message: "MineStack機能の対象ブロックが増えました！\n新たにメサで採掘可能な色付き堅焼き粘土がスタックされるようになります。"
lv122message: "MineStack機能の対象ブロックが増えました！\n新たに粘土がスタックされるようになります。"
lv127message: "MineStack機能の対象ブロックが増えました！\n新たに苔石がスタックされるようになります。"
lv132message: "MineStack機能の対象ブロックが増えました！\n新たに氷がスタックされるようになります。"
lv137message: "MineStack機能の対象ブロックが増えました！\n新たに粗い土とポドゾルがスタックされるようになります。"
lv142message: "MineStack機能の対象ブロックが増えました！\n新たにダークオークの木材とダークオークのフェンスがスタックされるようになります。"
lv147message: "MineStack機能の対象ブロックが増えました！\n新たにクモの巣と糸がスタックされるようになります。"
lv152message: "MineStack機能の対象ブロックが増えました！\n新たにレールがスタックされるようになります。"
lv157message: "MineStack機能の対象ブロックが増えました！\n新たに各種葉がスタックされるようになります。"
lv162message: "MineStack機能の対象ブロックが増えました！\n新たに雪ブロックがスタックされるようになります。"
lv167message: "MineStack機能の対象ブロックが増えました！\n新たに巨大キノコブロックがスタックされるようになります。"
lv172message: "MineStack機能の対象ブロックが増えました！\n新たに菌糸がスタックされるようになります。"
lv177message: "MineStack機能の対象ブロックが増えました！\n新たに各種苗木がスタックされるようになります。"

# サブホームポイント数の設定
# 3から変更しないで！！
subhomemax: 3

# 実績名の名称設定
Achv1001: "整地神"
Achv1002: "四天王"
Achv1003: "重鎮"
Achv1004: "大御所"
Achv1005: "LOVE!整地!"
Achv1006: "欲まみれ"
Achv1007: "整地に恋する"
Achv1008: "大地は友達"
Achv1009: "門戸を叩く"
Achv3001: "超克者"
Achv3002: "永遠の旅人"
Achv3003: "破壊神"
Achv3004: "理不尽な"
Achv3005: "枯れぬ野望"
Achv3006: "登頂者"
Achv3007: "不屈の"
Achv3008: "ミリオネア"
Achv3009: "夢追い人"
Achv3010: "高みを目指す"
Achv3011: "参戦者"
Achv4001: "ｼｬﾁｸﾉｷﾜﾐ"
Achv4002: "休日爆撃機"
Achv4003: "企業戦士"
Achv4004: "目覚めの夜"
Achv4005: "元気100倍"
Achv4006: "三日目の朝"
Achv4007: "完徹マン"
Achv4008: "さらば終電"
Achv4009: "減らぬ課題"
Achv4010: "期待の新人"
Achv6001: "狂信者"
Achv6002: "全身全霊"
Achv6003: "洗脳済"
Achv6004: "虜となった"
Achv6005: "魅惑の"
Achv6006: "投票魔"
Achv6007: "熱烈な"
Achv6008: "お気に入り"
Achv7001: "目指すは栄光"
Achv7002: "貫禄の王者"
Achv7003: "顕現の立役者"
Achv7004: "無から有へと"
Achv7005: "確かな一歩"
Achv8001: "時空の旅人"
Achv8002: "幸運の申し子"
Achv8003: "タスク撃墜王"
Achv9001: "お年玉"
Achv9002: "サンタさん"
Achv9003: "おそば"
Achv9004: "ヤギ族頭領"
Achv9005: "亀ではない"
Achv9006: "鬼"
Achv9007: "ガチビルダー"
Achv9008: "友チョコ０枚"
Achv9009: "魚類"
Achv9010: "どかんと一発"
Achv9011: "必要資金０円"
Achv9012: "平等主義"
Achv9013: "刈らないで"
Achv9014: " Iu999 "
Achv9015: "全科Ｃ評価"
Achv9016: "スッキリ。"

# デバッグモードの設定
# debugmode: 0=デバッグモードオフ, 1=デバッグモードオン
# 変更値を反映させるにはサーバを再起動するか/reloadしてください
debugmode: '0'

# デバッグモード(メビウス帽子専用)の設定
# debugmode: 0=デバッグモードオフ, 1=デバッグモードオン
# 変更値を反映させるにはサーバを再起動するか/reloadしてください
mebiusdebug: '0'

# ギガンティック→椎名林檎交換レートの設定
# デフォルト値はギガンティック1個につき椎名林檎4個
rategigantictoringo: '4'
