# seichiassist 設定ファイル
# このファイルを削除orリネームしてからサーバを起動するとデフォルトの設定ファイルが再生成されます(エラーが出たときは真っ先に試しましょう)

# MySQLデータベースへの接続設定
# xamppの設定を変えていなければデフォルトの値で問題ありません
host: 'localhost'
port: '3306'
db: 'seichiassist'
id: 'root'
pw: ''

# サーバ識別設定
# 複数サーバ構成にする場合はこの値をサーバごとに変更します
servernum: '1'

# 色々な設定、説明は割愛
defaultmineamount: '3'
minutespeedamount: '0.01'
onlineplayersamount: '0.5'
presentinterval: '1000'
dualbreaklevel: '10'
trialbreaklevel: '20'
explosionlevel: '30'
thunderstormlevel: '40'
blizzardlevel: '50'
meteolevel: '60'
gravitylevel: '100'
multipleidblockbreaklevel: '1'
dropexplevel1: '6'
dropexplevel2: '10'
dropexplevel3: '16'
dropexplevel4: '24'
dropexplevel5: '34'
dropexplevel6: '46'
dropexplevel7: '60'
dropexplevel8: '76'
dropexplevel9: '94'
dropexplevel10: '114'
passiveportalinventorylevel: '1'
dokodemoenderlevel: '25'

# MineStackの開放レベルの設定
minestacklevel1: '12'
minestacklevel2: '17'
minestacklevel3: '22'
minestacklevel4: '27'
minestacklevel5: '32'
minestacklevel6: '37'
minestacklevel7: '42'
minestacklevel8: '47'
minestacklevel9: '52'
minestacklevel10: '57'
minestacklevel11: '62'
minestacklevel12: '67'
minestacklevel13: '72'
minestacklevel14: '77'
minestacklevel15: '82'
minestacklevel16: '87'
minestacklevel17: '92'
minestacklevel18: '97'
minestacklevel19: '102'
minestacklevel20: '107'
minestacklevel21: '112'
minestacklevel22: '117'
minestacklevel23: '122'
minestacklevel24: '127'
minestacklevel25: '132'
minestacklevel26: '137'
minestacklevel27: '142'
minestacklevel28: '147'
minestacklevel29: '152'
minestacklevel30: '157'
minestacklevel31: '162'
minestacklevel32: '167'
minestacklevel33: '172'
minestacklevel34: '177'
minestacklevel35: '182'
minestacklevel36: '187'
minestacklevel37: '192'
minestacklevel38: '197'

# レベルアップ時にプレイヤーに表示されるメッセージの設定
lv1message: "整地鯖では整地をするとレベルが上がり、様々な恩恵が受けられます。\n初めての方は整地ワールドで掘ってレベルを上げてみましょう！\n木の棒を右クリックしてメニューを開き右上のビーコンボタンをクリック！"
lv2message: "おめでとうございます！最初のレベルアップです！\nレベル8に到達すると整地するだけで経験値がもらえるようになります。"
lv3message: "やけに早く掘れる気がする…？それは仕様です＾＾\n整地鯖では接続人数や採掘量に応じて採掘速度にブーストが掛かります。"
lv4message: "整地鯖では死んでもロストしません。気軽に冒険、整地してくださいね。\nそういえば当鯖の「ルール」もう確認しましたか？\n手遅れになる前に確認しておきましょうネ。木の棒メニューからどうぞ。"
lv5message: "Dynmapでどこに誰がいるのか、何があるのかなどを見ることができます。\nURLはこちら→http://seichi.click/d/DynmapLinks"
lv6message: "ブランチマイニングは資源ワールドでお願いします。\nスポーンワールドから行くことが出来ます。行き方覚えてますか？\n木の棒メニューのビーコンボタンをクリックするとすぐ行けますよ！"
lv7message: "あと300ブロックほど整地するとガチャ券を獲得できます！\nガチャ券を右クリックすると豪華景品が獲得できるかも？"
lv8message: "おめでとう！新しいパッシブスキル[マナ獲得]を解除しました。\n特定のブロック破壊で確率でマナを獲得できるようになりました！"
lv9message: "整地鯖をもっと良くするために、是非JPMCSに投票をお願いします。\n1日1回投票出来ます。投票すると様々な特典を受け取れます！\nURLはこちら→https://minecraft.jp/servers/54d3529e4ddda180780041a7/vote"
lv10message: "初めてのアクティブスキル[デュアルブレイク]を習得できます！\n習得するには木の棒メニューのスキルブックをクリック！\nレベル12に到達するとMineStack機能が使えるようになります。\nブロック破壊スキルでは溶岩も消去することができますが溶岩1個につきブロック10個分の耐久値を消費します。"
lv11message: "そろそろ家建てません…？自分の家はメインワールドで建てることができます。\n他人の保護の無い所に保護を設定してから建てましょう。\n保護方法は公式wikiに詳しい説明があります。木の棒メニューからどうぞ。\n自分のチェストは設定した保護内に置けば自動でロックされます。"
lv12message: "MineStack機能を解除しました！木の棒メニューから呼び出せます。\n対象ブロックを無限にスタック出来、いつでも取り出せます。\nレベル16に到達すると四次元ポケットが使えるようになります。"
lv13message: "建築の時など、採掘速度のブースト効果が邪魔な時は\n木の棒メニューから効果のONとOFFを変更できます。"
lv14message: "「ガチャ券がイチイチ地面に落っこちるのがうざい！」\nって人に朗報です。木の棒メニューからガチャ券の取得方法を変更できます。"
lv15message: "家を建てたら木の棒メニューからホームポイントを設定しておきましょう。\nどこからでもクリック1つで自宅へ瞬間移動できますよ！"
#lv17message: "MineStack機能の対象ブロックが増えました！\n新たに丸石と石がスタックされるようになります。"
lv18message: "整地の際に獲得できる経験値量が増えました。\n経験値量は10レベルごとに増加し、スキルがより長く使えるようになります！"
lv20message: "新しいアクティブスキル[トリアルブレイク]を習得できます！\n習得するには木の棒メニューのスキルブックをクリック！"
#lv22message: "MineStack機能の対象ブロックが増えました！\n新たに花崗岩と閃緑岩、安山岩がスタックされるようになります。"
lv25message: "どこでもエンダーチェスト機能を解除しました！\n木の棒メニューから呼び出せます。"
#lv27message: "MineStack機能の対象ブロックが増えました！\n新たに各種原木がスタックされるようになります。"
lv28message: "整地の際に獲得できる経験値量が増えました。"
lv30message: "新しいアクティブスキル[エクスプロージョン]を習得できます！\n習得するには木の棒メニューのスキルブックをクリック！"
#lv32message: "MineStack機能の対象ブロックが増えました！\n新たに砂利と砂、砂岩がスタックされるようになります。"
#lv37message: "MineStack機能の対象ブロックが増えました！\n新たにネザーラックとソウルサンドがスタックされるようになります。"
lv38message: "整地の際に獲得できる経験値量が増えました。"
lv40message: "新しいアクティブスキルを習得できます！\n習得するには木の棒メニューのスキルブックをクリック！\nツリーが分かれていますので、お好きなスキルをドウゾ。"
#lv42message: "MineStack機能の対象ブロックが増えました！\n新たに石炭と石炭鉱石がスタックされるようになります。"
lv46message: "四次元ポケットの容量が増加しました！"
#lv47message: "MineStack機能の対象ブロックが増えました！\n新たにエンドストーンがスタックされるようになります。"
lv48message: "整地の際に獲得できる経験値量が増えました。"
#lv52message: "MineStack機能の対象ブロックが増えました！\n新たに鉄鉱石と黒曜石がスタックされるようになります。"
lv56message: "四次元ポケットの容量が増加しました！"
#lv57message: "MineStack機能の対象ブロックが増えました！\n新たに氷塊がスタックされるようになります。"
lv58message: "整地の際に獲得できる経験値量が増えました。"
#lv62message: "MineStack機能の対象ブロックが増えました！\n新たにクォーツとクォーツ鉱石がスタックされるようになります。"
lv66message: "四次元ポケットの容量が増加しました！"
#lv67message: "MineStack機能の対象ブロックが増えました！\n新たにマグマブロックがスタックされるようになります。"
lv68message: "整地の際に獲得できる経験値量が増えました。"
#lv72message: "MineStack機能の対象ブロックが増えました！\n新たに金鉱石とグロウストーンがスタックされるようになります。"
#lv77message: "MineStack機能の対象ブロックが増えました！\n新たにオークの木材とオークのフェンスがスタックされるようになります。"
lv78message: "整地の際に獲得できる経験値量が増えました。"
#lv82message: "MineStack機能の対象ブロックが増えました！\n新たにレッドストーンとレッドストーン鉱石がスタックされるようになります。"
#lv87message: "MineStack機能の対象ブロックが増えました！\n新たにラピスラズリとラピスラズリ鉱石がスタックされるようになります。"
lv88message: "整地の際に獲得できる経験値量が増えました。"
#lv92message: "MineStack機能の対象ブロックが増えました！\n新たにダイヤモンドとダイヤモンド鉱石がスタックされるようになります。"
#lv97message: "MineStack機能の対象ブロックが増えました！\n新たにエメラルドとエメラルド鉱石がスタックされるようになります。"
lv98message: "整地の際に獲得できる経験値量が増えました。"
#lv107message: "MineStack機能の対象ブロックが増えました！\n新たに赤い砂と赤い砂岩がスタックされるようになります。"
#lv112message: "MineStack機能の対象ブロックが増えました！\n新たに堅焼き粘土がスタックされるようになります。"
#lv117message: "MineStack機能の対象ブロックが増えました！\n新たにメサで採掘可能な色付き堅焼き粘土がスタックされるようになります。"
#lv122message: "MineStack機能の対象ブロックが増えました！\n新たに粘土がスタックされるようになります。"
#lv127message: "MineStack機能の対象ブロックが増えました！\n新たに苔石がスタックされるようになります。"
#lv132message: "MineStack機能の対象ブロックが増えました！\n新たに氷がスタックされるようになります。"
#lv137message: "MineStack機能の対象ブロックが増えました！\n新たに粗い土とポドゾルがスタックされるようになります。"
#lv142message: "MineStack機能の対象ブロックが増えました！\n新たにダークオークの木材とダークオークのフェンスがスタックされるようになります。"
#lv147message: "MineStack機能の対象ブロックが増えました！\n新たにクモの巣と糸がスタックされるようになります。"
#lv152message: "MineStack機能の対象ブロックが増えました！\n新たにレールがスタックされるようになります。"
#lv157message: "MineStack機能の対象ブロックが増えました！\n新たに各種葉がスタックされるようになります。"
#lv162message: "MineStack機能の対象ブロックが増えました！\n新たに雪ブロックがスタックされるようになります。"
#lv167message: "MineStack機能の対象ブロックが増えました！\n新たに巨大キノコブロックがスタックされるようになります。"
#lv172message: "MineStack機能の対象ブロックが増えました！\n新たに菌糸がスタックされるようになります。"
#lv177message: "MineStack機能の対象ブロックが増えました！\n新たに各種苗木がスタックされるようになります。"

# サブホームポイント数の設定
# 7以下に設定
subhomemax: 5

# 実績名の名称設定
# 中パーツ(初期開放)
AchvB9901: "は"
AchvB9902: "な"
AchvB9903: "と"
AchvB9904: "に"
AchvB9905: "の"
AchvB9906: "も"
AchvB9907: "が"
AchvB9908: "で"
AchvB9909: "を"
AchvB9910: "から"
# 中パーツ(購入用)
AchvB9911: "的"
AchvB9912: "・"
AchvB9913: "＆"
AchvB9914: "対"
AchvB9915: "＝"
AchvB9916: "☆"
AchvB9917: "～"
AchvB9918: "ぬ"
AchvB9919: "より"
AchvB9920: "風"
AchvB9921: "式"
AchvB9922: "－"
AchvB9923: "＋"
AchvB9924: "×"
AchvB9925: "÷"
AchvB9926: "＠"
AchvB9927: "†"
AchvB9928: "♡"
AchvB9929: "."
AchvB9930: "！"
AchvB9931: "？"
AchvB9932: "＃"
# 前後パーツ(購入用)
AchvA9801: "お兄さん"
AchvC9801: "お兄さん"
AchvA9802: "戦隊"
AchvC9802: "戦隊"
AchvA9803: "軍"
AchvC9803: "軍"
AchvA9804: "うどん"
AchvC9804: "うどん"
AchvA9805: "厨二病"
AchvC9805: "厨二病"
AchvA9806: "現世"
AchvC9806: "現世"
AchvA9807: "天界"
AchvC9807: "天界"
AchvA9808: "冥界"
AchvC9808: "冥界"
AchvA9809: "地獄"
AchvC9809: "地獄"
AchvA9810: "最終兵器"
AchvC9810: "最終兵器"
AchvA9811: "ごりら"
AchvC9811: "ごりら"
AchvA9812: "うほうほ"
AchvC9812: "うほうほ"
AchvA9813: "暑い"
AchvC9813: "暑い"
AchvA9814: "寒い"
AchvC9814: "寒い"
AchvA9815: "笑う"
AchvC9815: "笑う"
AchvA9816: "泣く"
AchvC9816: "泣く"
AchvA9817: "怒る"
AchvC9817: "怒る"
AchvA9818: "最初"
AchvC9818: "最初"
AchvA9819: "最後"
AchvC9819: "最後"
AchvA9820: "ァ！"
AchvC9820: "ァ！"
AchvA9821: "ィ！"
AchvC9821: "ィ！"
AchvA9822: "ゥ！"
AchvC9822: "ゥ！"
AchvA9823: "ェ！"
AchvC9823: "ェ！"
AchvA9824: "ォ！"
AchvC9824: "ォ！"
AchvA9825: "茸"
AchvC9825: "茸"
AchvA9826: "筍"
AchvC9826: "筍"
AchvA9827: "キラー"
AchvC9827: "キラー"
AchvA9828: "ビーム"
AchvC9828: "ビーム"
AchvA9829: "バリア"
AchvC9829: "バリア"
AchvA9830: "定食"
AchvC9830: "定食"
AchvA9831: "襲来"
AchvC9831: "襲来"
AchvA9832: "撃退"
AchvC9832: "撃退"
# 整地ランキング実績
AchvA1001: "整地神"
AchvC1001: "整地神"
AchvA1002: "四天王"
AchvC1002: "四天王"
AchvA1003: "重鎮"
AchvC1003: "重鎮"
AchvA1004: "大御所"
AchvC1004: "大御所"
AchvA1005: "ラヴ！"
AchvC1005: "整地"
AchvA1006: "欲まみれ"
AchvC1006: "欲まみれ"
AchvA1007: "整地"
AchvC1007: "恋する"
AchvA1008: "大地"
AchvC1008: "友達"
AchvA1009: "門戸"
AchvC1009: "叩く"
AchvA1010: "百傑"
AchvC1010: "百傑"
AchvA1011: "超人"
AchvC1011: "挑む"
AchvA1012: "継続"
AchvC1012: "力なり"
#スターレベル実績
# 整地量実績
AchvA3001: "超克者"
AchvC3001: "超克者"
AchvA3002: "永遠"
AchvC3002: "旅人"
AchvA3003: "破壊神"
AchvC3003: "破壊神"
AchvA3004: "理不尽"
AchvC3004: "理不尽"
AchvA3005: "枯れぬ"
AchvC3005: "野望"
AchvA3006: "登頂者"
AchvC3006: "登頂者"
AchvA3007: "不屈"
AchvC3007: "不屈"
AchvA3008: "ミリオネア"
AchvC3008: "ミリオネア"
AchvA3009: "夢追い"
AchvC3009: "人"
AchvA3010: "高み"
AchvC3010: "目指す"
AchvA3011: "参戦者"
AchvC3011: "参戦者"
AchvA3012: "いざ"
AchvC3012: "新天地"
AchvA3013: "努力"
AchvC3013: "化身"
AchvA3014: "虚無"
AchvC3014: "連れる"
AchvA3015: "敗北者"
AchvC3015: "敗北者"
AchvA3016: "開拓者"
AchvC3016: "開拓者"
AchvA3017: "侵略者"
AchvC3017: "侵略者"
AchvA3018: "蹂躙者"
AchvC3018: "蹂躙者"
AchvA3019: "真破壊神"
AchvC3019: "真破壊神"
# ログイン時間実績
AchvA4001: "社蓄"
AchvC4001: "極み"
AchvA4002: "休日"
AchvC4002: "爆撃機"
AchvA4003: "企業"
AchvC4003: "戦士"
AchvA4004: "目覚め"
AchvC4004: "夜"
AchvA4005: "元気"
AchvC4005: "百倍"
AchvA4006: "三日目"
AchvC4006: "朝"
AchvA4007: "完徹"
AchvC4007: "マン"
AchvA4008: "さらば"
AchvC4008: "終電"
AchvA4009: "減らぬ"
AchvC4009: "課題"
AchvA4010: "期待"
AchvC4010: "新人"
AchvA4011: "道"
AchvC4011: "続く"
AchvA4012: "広がる"
AchvC4012: "限界"
AchvA4013: "過ぎ去る"
AchvC4013: "過去"
AchvA4014: "時"
AchvC4014: "開拓者"
AchvA4015: "止まれない"
AchvC4015: "止まれない"
AchvA4016: "挫けず"
AchvC4016: "走る"
AchvA4017: "一年分"
AchvC4017: "一年分"
AchvA4018: "次元"
AchvC4018: "圧縮"
AchvA4019: "失った"
AchvC4019: "ブレーキ"
AchvA4020: "最早"
AchvC4020: "人生"
AchvA4021: "ルーチン"
AchvC4021: "ワーク"
AchvA4022: "手段"
AchvC4022: "目的"
AchvA4023: "見えぬ"
AchvC4023: "終着点"
# 連続ログイン実績
AchvA5001: "絶え間"
AchvB5001: "なき"
AchvA5002: "永久"
AchvC5002: "ループ"
AchvA5003: "義務感"
AchvC5003: "義務感"
AchvA5004: "大好き"
AchvC5004: "なのです"
AchvA5005: "もはや"
AchvC5005: "日課"
AchvA5006: "マイ"
AchvC5006: "ブーム"
AchvA5007: "止まらない"
AchvC5007: "止まらない"
AchvA5008: "お楽しみ"
AchvC5008: "お楽しみ"
# 通算ログイン実績
AchvA5101: "いざ"
AchvC5101: "二週目"
AchvA5102: "終わり"
AchvC5102: "見えた"
AchvA5103: "無欠勤"
AchvC5103: "無欠勤"
AchvA5104: "百"
AchvC5104: "軌跡"
AchvA5105: "ここ"
AchvC5105: "おうち"
AchvA5106: "忠誠心"
AchvC5106: "忠誠心"
AchvA5107: "月"
AchvC5107: "捧げる"
AchvA5108: "とにかく"
AchvC5108: "入る"
AchvA5109: "常連"
AchvC5109: "常連"
AchvA5110: "顔見知り"
AchvC5110: "顔見知り"
AchvA5111: "再び"
AchvC5111: "再び"
AchvA5112: "何でも"
AchvC5112: "知ってる"
AchvA5113: "無尽蔵"
AchvC5113: "気合"
AchvA5114: "親子"
AchvC5114: "揃って"
AchvA5115: "役員会"
AchvC5115: "役員会"
AchvA5116: "三度目"
AchvC5116: "正直"
AchvA5117: "いつまで"
AchvC5117: "やろうか"
AchvA5118: "昇給"
AchvC5118: "まだですか"
AchvA5119: "歴史"
AchvC5119: "生き証人"
AchvA5120: "石の上"
AchvB5120: "にも"
AchvC5120: "三年"
# 投票数実績
AchvA6001: "狂信者"
AchvC6001: "狂信者"
AchvA6002: "全身"
AchvC6002: "全霊"
AchvA6003: "洗脳済"
AchvC6003: "洗脳済"
AchvA6004: "虜"
AchvC6004: "なった"
AchvA6005: "魅惑"
AchvA6006: "投票"
AchvC6006: "魔"
AchvA6007: "熱烈"
AchvA6008: "お気に入り"
AchvC6008: "お気に入り"
# 公式イベント実績
AchvA7001: "目指す"
AchvC7001: "栄光"
AchvA7002: "貫禄"
AchvC7002: "王者"
AchvA7003: "顕現"
AchvC7003: "立役者"
AchvA7004: "無"
AchvB7004: "無から有へと"
AchvC7004: "有"
AchvA7005: "確か"
AchvC7005: "一歩"
AchvA7006: "春"
AchvC7006: "妖精"
AchvA7007: "匠"
AchvC7007: "挑戦状"
AchvA7008: "神器"
AchvC7008: "造形主"
AchvA7009: "生誕祭"
AchvC7009: "採掘王"
AchvA7010: "凍てつく"
AchvC7010: "情熱"
AchvA7011: "灼熱"
AchvV7011: "海岸線"
AchvA7012: "不沈"
AchvC7012: "邸宅"
AchvA7013: "雅"
AchvC7013: "雅"
AchvA7014: "トレビアン"
AchvC7014: "トレビアン"
AchvA7015: "未来"
AchvC7015: "繋ぐ"
AchvA7016: "妄想"
AchvC7016: "炸裂"
AchvA7017: "神秘"
AchvC7017: "芸術家"
AchvA7018: "自由"
AchvC7018: "描く"
AchvA7019: "情報屋"
AchvC7019: "ぴっぴ"
AchvA7020: "ペペロン"
AchvC7020: "チーノ"
AchvA7021: "奇跡"
AchvC7021: "使徒"
AchvA7022: "もしゃ"
AchvC7022: "もしゃ"
AchvA7023: "かみ"
AchvC7023: "つかい"
AchvA7024: "舞い散る"
AchvC7024: "緑葉"
AchvA7025: "ぬぬぬ"
AchvC7025: "森"
AchvA7026: "鋼鉄"
AchvC7026: "意志"
AchvA7027: "ベスト"
AchvC7027: "エイジ"
AchvA7901: "幕張"
AchvB7901: "→"
AchvC7901: "整地鯖"
AchvA7902: "顔バレ"
AchvC7902: "しました"
AchvA7903: "三次元"
AchvC7903: "住人"
AchvA7904: "やべー奴"
AchvC7904: "いた"
AchvA7905: "まいん"
AchvC7905: "ちゃん"
AchvA7906: "まいくら"
AchvC7906: "ひろば"
# 極秘実績
AchvA8001: "時空"
AchvC8001: "旅人"
AchvA8002: "幸運"
AchvC8002: "申し子"
AchvA8003: "タスク"
AchvC8003: "撃墜王"
# 記念日実績
AchvA9001: "お年玉"
AchvC9001: "お年玉"
AchvA9002: "サンタ"
AchvC9002: "さん"
AchvA9003: "おそば"
AchvC9003: "おそば"
AchvA9004: "ヤギ"
AchvB9004: "族"
AchvC9004: "頭領"
AchvA9005: "亀"
AchvC9005: "ではない"
AchvA9006: "鬼"
AchvC9006: "鬼"
AchvA9007: "創立者"
AchvC9007: "創立者"
AchvA9008: "友チョコ"
AchvC9008: "０枚"
AchvA9009: "魚類"
AchvC9009: "魚類"
AchvA9010: "どかん"
AchvC9010: "一発"
AchvA9011: "必要資金"
AchvC9011: "０円"
AchvA9012: "平等"
AchvC9012: "主義"
AchvA9013: "刈らないで"
AchvC9013: "刈らないで"
AchvB9014: " Iu999 "
AchvA9015: "全科"
AchvC9015: "Ｃ評価"
AchvA9016: "塵"
AchvB9016: "しか"
AchvC9016: "残さん"
AchvA9017: "余す所"
AchvC9017: "なき"
AchvA9018: "紙耐久"
AchvC9018: "紙耐久"
AchvA9019: "空気"
AchvC9019: "美味也"
AchvA9020: "溢れ出る"
AchvC9020: "母性"
AchvA9021: "始点"
AchvC9021: "分岐点"
AchvA9022: "褪せない"
AchvC9022: "記録"
AchvA9023: "滲み出る"
AchvC9023: "父性"
AchvA9024: "ぐるっと"
AchvC9024: "回って"
AchvA9025: "ｖ"
AchvB9025: "(・v・)"
AchvC9025: "ｖ"
AchvA9026: "繋がる"
AchvC9026: "願い"
AchvA9027: "過密"
AchvC9027: "地帯"
AchvA9028: "食卓"
AchvB9028: "からの"
AchvC9028: "食卓"
AchvA9029: "ミン"
AchvB9029: "ミン"
AchvC9029: "ミン"
AchvA9030: "ジャングル"
AchvC9030: "王"
AchvA9031: "全力"
AchvC9031: "逃げて"
AchvA9032: "全部"
AchvC9032: "焦げた"
AchvA9033: "団子"
AchvC9033: "団子"
AchvA9034: "全額"
AchvC9034: "投資"
AchvA9035: "無尽蔵"
AchvC9035: "気力"
AchvA9036: "猛毒"
AchvC9036: "直撃"

# デバッグモードの設定
# debugmode: 0=デバッグモードオフ, 1=デバッグモードオン
# 変更値を反映させるにはサーバを再起動するか/reloadしてください
debugmode: '0'

# デバッグモード(メビウス帽子専用)の設定
# debugmode: 0=デバッグモードオフ, 1=デバッグモードオン
# 変更値を反映させるにはサーバを再起動するか/reloadしてください
mebiusdebug: '0'

# ギガンティック→椎名林檎交換レートの設定
# デフォルト値はギガンティック1個につき椎名林檎4個
rategigantictoringo: '4'

# ギガンティック・フィーバーの効果継続時間を指定します。(単位:分)
gigantic_fever_minutes: 120

# グリッド式保護メニュー経由で保護が可能なワールド名一覧
# ここに記載されたワールド名ではworldguard.region.claimパーミッションが無くても
# グリッド式保護メニュー経由で保護が可能になります
GridProtectEnableWorld:
 - world_test

# グリッドで指定可能な最大ユニット合計数の設定
# (15ブロック=1ユニット)
## デフォルト値
GridLimitDefault: '32'
## ワールド毎の値(ここにないワールドはDefault値を見る)
GridLimitPerWorld:
  world: '16'
  world_2: '32'

#グリッド式保護のテンプレート保存最大数
GridTemplateKeepAmount: '5'

##自動再生成時の設定
#道のY座標
road_Y: 70
#道の長さ(チャンク単位)
road_length: 8
#道の上の空洞の高さ
space_height: 5
#道のブロックID
road_blockid: 98
#道のブロックダメージ値
road_blockdamage: 0
#再生成時のワールドサイズ
world_size: 2000

#貢献度1当たりのマナ増加量
contribute_added_mana: 10

#期間限定ログインイベント(ここの設定を変更することで毎年使いまわしが可能です。)
#日付は必ず"西暦4桁-月2桁-日2桁"で入力すること!!
LimitedLoginEvent:
  #開始日(この日からカウントされるようになります)
  EventStart: "2019/03/01"
  #終了日(この日が最後のカウント対象になります)
  EventEnd: "2019/03/31"
  
  #報酬設定
  #DAY0のデータは毎日配布されます
  #それ以外のデータは、期間内の累計ログイン数がその値になった日のみ配布されます
  #Itemで配布内容を、Amountで数量を指定します
  DAY0_Item: "1"
  DAY0_Amount: "30"
  DAY20_Item: "1"
  DAY20_Amount: "100"
  #Tips:[Item]内容一覧(追加・変更はコード修正が必要です)
  #"1":ガチャ券

#お正月イベント関連(ここの設定を変更することで毎年使いまわしが可能です。)
#日付は必ず"西暦4桁-月2桁-日2桁"で入力すること!!
NewYearEvent:
  #お正月用「年越し蕎麦」配布日
  GivingNewYearSobaDay: "2017-12-31"
  #お正月用「年越し蕎麦」Loreに記入される年
  NewYearSobaYear: "2017"
  #お年玉袋ドロップ開始日/終了日
  DropNewYearBagStartDay: "2018-01-01"
  DropNewYearBagEndDay: "2018-01-31"
  #お年玉袋ドロップ数(1/nブロック)
  NewYearBagDropProbability: 500
  #(お年玉袋ItemNBT識別用);基本的に来年度の年を入力してください。
  NewYear: "2018"
  #正月リンゴの使用可能期限
  NewYearAppleStartDay: "2018-01-01"
  NewYearAppleEndDay: "2018-02-07"

#GiganticBerserk
#1分間上限
GBLimit: 20

#各種URL
Url:
  official: "https://www.seichi.network/gigantic"
  rule: "https://www.seichi.network/rule"
  map: "https://www.seichi.network/map"
  jms: "https://minecraft.jp/servers/54d3529e4ddda180780041a7"
