# seichiassist 設定ファイル
# このファイルを削除orリネームしてからサーバを起動するとデフォルトの設定ファイルが再生成されます(エラーが出たときは真っ先に試しましょう)

# MySQLデータベースへの接続設定
# xamppの設定を変えていなければデフォルトの値で問題ありません
host: 'localhost'
port: '3306'
db: 'seichiassist'
id: 'root'
pw: ''

# サーバ識別設定
# 複数サーバ構成にする場合はこの値をサーバごとに変更します
servernum: '1'

# 色々な設定、説明は割愛
defaultmineamount: '3'
minutespeedamount: '0.01'
onlineplayersamount: '0.5'
presentinterval: '1000'
dualbreaklevel: '10'
trialbreaklevel: '20'
explosionlevel: '30'
thunderstormlevel: '40'
blizzardlevel: '50'
meteolevel: '60'
gravitylevel: '100'
multipleidblockbreaklevel: '1'
dropexplevel1: '6'
dropexplevel2: '10'
dropexplevel3: '16'
dropexplevel4: '24'
dropexplevel5: '34'
dropexplevel6: '46'
dropexplevel7: '60'
dropexplevel8: '76'
dropexplevel9: '94'
dropexplevel10: '114'
passiveportalinventorylevel: '1'
dokodemoenderlevel: '25'

# MineStackの開放レベルの設定
minestacklevel1: '12'
minestacklevel2: '17'
minestacklevel3: '22'
minestacklevel4: '27'
minestacklevel5: '32'
minestacklevel6: '37'
minestacklevel7: '42'
minestacklevel8: '47'
minestacklevel9: '52'
minestacklevel10: '57'
minestacklevel11: '62'
minestacklevel12: '67'
minestacklevel13: '72'
minestacklevel14: '77'
minestacklevel15: '82'
minestacklevel16: '87'
minestacklevel17: '92'
minestacklevel18: '97'
minestacklevel19: '102'
minestacklevel20: '107'
minestacklevel21: '112'
minestacklevel22: '117'
minestacklevel23: '122'
minestacklevel24: '127'
minestacklevel25: '132'
minestacklevel26: '137'
minestacklevel27: '142'
minestacklevel28: '147'
minestacklevel29: '152'
minestacklevel30: '157'
minestacklevel31: '162'
minestacklevel32: '167'
minestacklevel33: '172'
minestacklevel34: '177'
minestacklevel35: '182'
minestacklevel36: '187'
minestacklevel37: '192'
minestacklevel38: '197'

# レベルアップ時にプレイヤーに表示されるメッセージの設定
lv1message: "整地鯖では整地をするとレベルが上がり、様々な恩恵が受けられます。\n初めての方は整地ワールドで掘ってレベルを上げてみましょう！\n木の棒を右クリックしてメニューを開き右上のビーコンボタンをクリック！"
lv2message: "おめでとうございます！最初のレベルアップです！\nレベル8に到達すると整地するだけで経験値がもらえるようになります。"
lv3message: "やけに早く掘れる気がする…？それは仕様です＾＾\n整地鯖では接続人数や採掘量に応じて採掘速度にブーストが掛かります。"
lv4message: "整地鯖では死んでもロストしません。気軽に冒険、整地してくださいね。\nそういえば当鯖の「ルール」もう確認しましたか？\n手遅れになる前に確認しておきましょうネ。木の棒メニューからどうぞ。"
lv5message: "Dynmapでどこに誰がいるのか、何があるのかなどを見ることができます。\nURLはこちら→http://seichi.click/d/DynmapLinks"
lv6message: "各ワールドへの移動方法は覚えていますか？\n木の棒メニューのビーコンボタンをクリックするとすぐ行けますよ！"
lv7message: "あと300ブロックほど整地するとガチャ券を獲得できます！\nガチャ券を右クリックすると豪華景品が獲得できるかも？"
lv8message: "おめでとう！新しいパッシブスキル[マナ獲得]を解除しました。\n特定のブロック破壊で確率でマナを獲得できるようになりました！"
lv9message: "整地鯖をもっと良くするために、是非JPMCSに投票をお願いします。\n1日1回投票出来ます。投票すると様々な特典を受け取れます！\nURLはこちら→https://minecraft.jp/servers/54d3529e4ddda180780041a7/vote"
lv10message: "初めてのアクティブスキル[デュアルブレイク]を習得できます！\n習得するには木の棒メニューのスキルブックをクリック！\nレベル12に到達するとMineStack機能が使えるようになります。\nブロック破壊スキルでは溶岩も消去することができますが溶岩1個につきブロック10個分の耐久値を消費します。"
lv11message: "そろそろ家建てません…？自分の家はメインワールドで建てることができます。\n他人の保護の無い所に保護を設定してから建てましょう。\n保護方法は公式wikiに詳しい説明があります。木の棒メニューからどうぞ。\n自分のチェストは設定した保護内に置けば自動でロックされます。"
lv12message: "MineStack機能を解除しました！木の棒メニューから呼び出せます。\n対象ブロックを無限にスタック出来、いつでも取り出せます。\nレベル16に到達すると四次元ポケットが使えるようになります。"
lv13message: "建築の時など、採掘速度のブースト効果が邪魔な時は\n木の棒メニューから効果のONとOFFを変更できます。"
lv14message: "「ガチャ券がイチイチ地面に落っこちるのがうざい！」\nって人に朗報です。木の棒メニューからガチャ券の取得方法を変更できます。"
lv15message: "家を建てたら木の棒メニューからホームポイントを設定しておきましょう。\nどこからでもクリック1つで自宅へ瞬間移動できますよ！"
lv18message: "整地の際に獲得できる経験値量が増えました。\n経験値量は10レベルごとに増加し、スキルがより長く使えるようになります！"
lv20message: "新しいアクティブスキル[トリアルブレイク]を習得できます！\n習得するには木の棒メニューのスキルブックをクリック！"
lv25message: "どこでもエンダーチェスト機能を解除しました！\n木の棒メニューから呼び出せます。"
lv28message: "整地の際に獲得できる経験値量が増えました。"
lv30message: "新しいアクティブスキル[エクスプロージョン]を習得できます！\n習得するには木の棒メニューのスキルブックをクリック！"
lv38message: "整地の際に獲得できる経験値量が増えました。"
lv40message: "新しいアクティブスキルを習得できます！\n習得するには木の棒メニューのスキルブックをクリック！\nツリーが分かれていますので、お好きなスキルをドウゾ。"
lv46message: "四次元ポケットの容量が増加しました！"
lv48message: "整地の際に獲得できる経験値量が増えました。"
lv56message: "四次元ポケットの容量が増加しました！"
lv58message: "整地の際に獲得できる経験値量が増えました。"
lv66message: "四次元ポケットの容量が増加しました！"
lv68message: "整地の際に獲得できる経験値量が増えました。"
lv78message: "整地の際に獲得できる経験値量が増えました。"
lv88message: "整地の際に獲得できる経験値量が増えました。"
lv98message: "整地の際に獲得できる経験値量が増えました。"

# サブホームポイント数の設定
# 7以下に設定
subhomemax: 5

# 実績名の名称設定 -> Nicknames.scalaを参照すること

# デバッグモードの設定
# debugmode: 0=デバッグモードオフ, 1=デバッグモードオン
# 変更値を反映させるにはサーバを再起動するか/reloadしてください
debugmode: '0'

# デバッグモード(メビウス帽子専用)の設定
# debugmode: 0=デバッグモードオフ, 1=デバッグモードオン
# 変更値を反映させるにはサーバを再起動するか/reloadしてください
mebiusdebug: '0'

# ギガンティック→椎名林檎交換レートの設定
# デフォルト値はギガンティック1個につき椎名林檎4個
rategigantictoringo: '4'

# ギガンティック・フィーバーの効果継続時間を指定します。(単位:分)
gigantic_fever_minutes: 120

# グリッド式保護メニュー経由で保護が可能なワールド名一覧
# ここに記載されたワールド名ではworldguard.region.claimパーミッションが無くても
# グリッド式保護メニュー経由で保護が可能になります
GridProtectEnableWorld:
  - world_test

# グリッドで指定可能な最大ユニット合計数の設定
# (15ブロック=1ユニット)
## デフォルト値
GridLimitDefault: '32'
## ワールド毎の値(ここにないワールドはDefault値を見る)
GridLimitPerWorld:
  world: '16'
  world_2: '32'

#グリッド式保護のテンプレート保存最大数
GridTemplateKeepAmount: '5'

##自動再生成時の設定
#道のY座標
road_Y: 70
#道の長さ(チャンク単位)
road_length: 8
#道の上の空洞の高さ
space_height: 5
#道のブロックID
road_blockid: 98
#道のブロックダメージ値
road_blockdamage: 0
#再生成時のワールドサイズ
world_size: 2000

#貢献度1当たりのマナ増加量
contribute_added_mana: 10

#期間限定ログインイベント(ここの設定を変更することで毎年使いまわしが可能です。)
#日付は必ず"西暦4桁/月2桁/日2桁"で入力すること!!
LimitedLoginEvent:
  #開始日(この日からカウントされるようになります)
  EventStart: "2019/03/01"
  #終了日(この日が最後のカウント対象になります)
  EventEnd: "2019/03/31"

  #報酬設定
  #DAY0のデータは毎日配布されます
  #それ以外のデータは、期間内の累計ログイン数がその値になった日のみ配布されます
  #Itemで配布内容を、Amountで数量を指定します
  DAY0_Item: "1"
  DAY0_Amount: "30"
  DAY20_Item: "1"
  DAY20_Amount: "100"
  #Tips:[Item]内容一覧(追加・変更はコード修正が必要です)
  #"1":ガチャ券

#お正月イベント関連(ここの設定を変更することで毎年使いまわしが可能です。)
#日付は必ず"西暦4桁-月2桁-日2桁"で入力すること!!
NewYearEvent:
  #お正月用「年越し蕎麦」配布日
  GivingNewYearSobaDay: "2017-12-31"
  #お正月用「年越し蕎麦」Loreに記入される年
  NewYearSobaYear: "2017"
  #お年玉袋ドロップ開始日/終了日
  DropNewYearBagStartDay: "2018-01-01"
  DropNewYearBagEndDay: "2018-01-31"
  #お年玉袋ドロップ数(1/nブロック)
  NewYearBagDropProbability: 500
  #(お年玉袋ItemNBT識別用);基本的に来年度の年を入力してください。
  NewYear: "2018"
  #正月リンゴの使用可能期限
  NewYearAppleStartDay: "2018-01-01"
  NewYearAppleEndDay: "2018-02-07"

#GiganticBerserk
#1分間上限
GBLimit: 20

#各種URL
Url:
  official: "https://www.seichi.network/gigantic"
  rule: "https://www.seichi.network/rule"
  map: "https://www.seichi.network/map"
  jms: "https://minecraft.jp/servers/54d3529e4ddda180780041a7"

#Fly時の1分辺りの経験値消費量
flyexp: '50'

#ブロックを並べるスキル
blocklineup:
  level: '15'
  mana_mag: '0.0'
  minestack_level: '30'

#範囲設置スキル
ZoneSetSkill:
  level: '15'
  minestack: '30'

#スキルを使って並べた時のブロックカウント倍率
BlockCountMag: '0.2'

# MineStackブロック一括クラフト
minestack_BlockCraft:
  level1: '25'
  level2: '35'
  level3: '45'

#ブロック設置カウントの1分上限
BuildNum1minLimit: '256'
