name: publish develop build

on:
  push:
    branches:
      - develop

jobs:
  publish_build:
    runs-on: ubuntu-22.04
    steps:
      - name: Publish develop build
        env:
          SEICHIASSIST_DOWNLOADER_TOKEN: ${{ secrets.SEICHIASSIST_DOWNLOADER_TOKEN }}
        run: |
          curl -s -X 'POST' 'http://localhost/publish/develop' \
          -H 'accept: */*' \
          -H 'Authorization: Bearer $SEICHIASSIST_DOWNLOADER_TOKEN'
